<?php
use Magento\Framework\Escaper;
use Jajuma\PotCustomers\Block\Customers;

/** @var $block Customers */
/** @var $escaper Escaper */

//$magewire = $block->getMagewire();
$lastXHours = $block->getLastXHours();
$numberNewCustomers = number_format($block->getNumberNewCustomers(), 0, '', '.');
$totalCustomers = number_format($block->getTotalCustomers(), 0, '', '.');
$pendingCustomers = number_format($block->getPendingCustomers(), 0, '', '.');
$customersOnline = number_format($block->getCustomersOnline(), 0, '', '.');
$guestsOnline = number_format($block->getGuestsOnline(), 0, '', '.');
?>

<div id="jajuma_pot_customers" class="jajuma-pot-customers">
    <span class="powertoys-widget-title title-transparent"><?= 'Customers' ?></span>
    <div class="pot-customers-detail">
        <div class="pot-customers-new">
            <label><?= 'New' ?></label>
            <span><?= $numberNewCustomers ?></span>
        </div>
        <div class="pot-customers-total">
            <label><?= 'Total' ?></label>
            <span><?= $totalCustomers ?></span>
        </div>
        <div class="pot-customers-pending">
            <label><?= 'Pending' ?></label>
            <span><?= $pendingCustomers ?></span>
        </div>
        <div class="pot-customers-online">
            <label><?= 'Online' ?></label>
            <span><?= $customersOnline ?> / <?= $guestsOnline ?></span>
        </div>
        <span class="pot-customers-online-text"><?= '(Logged / Guests)' ?></span>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z" />
    </svg>
</div>

<style>
    .widget-item.widget-item-pot_customers {
        position: relative;
        background: linear-gradient(to bottom right,#534f88 0%,#1b2257 80%) !important;
        color: #fff;
        overflow: hidden;
    }

    .widget-item-pot_customers .title {
        margin-bottom: 10px;
        font-size: 12px;
        padding: 1px 6px;
        color: #fff;
        background: transparent;
        border: 1px solid #fff;
        border-radius: 16px;
        height: 20px;
        display: inline-block;
        width: fit-content;
    }

    .jajuma-pot-customers {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

    .jajuma-pot-customers > * {
        position: relative;
        z-index: 1;
    }

    .jajuma-pot-customers svg {
        position: absolute;
        width: 100%;
        height: 100%;
        right: -5px;
        opacity: .025;
        top: -5px;
        z-index: 0;
    }

    .jajuma-pot-customers div {
        width: 100%;
        overflow: hidden;
    }

    .jajuma-pot-customers div label {
        width: 50%;
        float: left;
        text-align: left;
    }

    .jajuma-pot-customers div span {
        width: 50%;
        float: right;
        text-align: right;
    }

    .jajuma-pot-customers .pot-customers-detail {
        display: flex;
        flex-direction: column;
        flex: 1;
        justify-content: space-between;
    }

    .jajuma-pot-customers .pot-customers-new {
        font-size: 24px;
        font-weight: 700;
        border-bottom: 1px solid white;
        padding-bottom: 2px;
    }

    .jajuma-pot-customers .pot-customers-total {
        font-size: 14px;
        padding-top: 3px;
    }

    .jajuma-pot-customers .pot-customers-pending {
        font-size: 14px;
        padding-bottom: 3px;
        border-bottom: 1px solid white;
    }

    .jajuma-pot-customers .pot-customers-online {
        font-size: 18px;
        font-weight: 500;
        padding-top: 5px;
    }

    .jajuma-pot-customers .pot-customers-online-text {
        width: 100%;
        text-align: right;
        font-size: 12px;
    }
</style>
